# Generated by Django 6.0.4 on 2026-05-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
