# Generated by Django 6.0.4 on 2026-05-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
